const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shell = (title, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Prompt Theater</title><style>
*{box-sizing:border-box}body{margin:0;background:#080a0f;color:#f4f1ea;font:16px/1.55 system-ui,-apple-system,sans-serif}a{color:#ff816f}.wrap{max-width:1080px;margin:auto;padding:24px}.nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px}.brand{font-weight:800;letter-spacing:.08em;color:#fff;text-decoration:none}.muted{color:#9aa0ac}.hero{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,1fr);gap:25px}.panel{background:#11151d;border:1px solid #252a35;border-radius:14px;padding:20px}video{width:100%;aspect-ratio:16/9;background:#000;border-radius:10px}.live{color:#ff675b;font-size:13px;font-weight:800}.live:before{content:'● ';animation:p 1.4s infinite}@keyframes p{50%{opacity:.35}}h1{font-size:30px;margin:8px 0 16px}textarea{width:100%;min-height:120px;background:#090c12;color:#fff;border:1px solid #363d49;border-radius:8px;padding:12px;font:inherit}button{width:100%;padding:13px;background:#ff675b;color:#160705;border:0;border-radius:8px;font-weight:800;font-size:16px;cursor:pointer}.scene{border-top:1px solid #252a35;padding:14px 0}.status{text-transform:uppercase;font-size:11px;letter-spacing:.08em;color:#9aa0ac}.legal{max-width:700px}.legal h2{margin-top:32px}.notice{border-color:#3d6b4a;background:#101c14;margin-bottom:24px}@media(max-width:760px){.hero{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><nav class="nav"><a class="brand" href="/">PROMPT THEATER</a><span><a href="/privacy">Privacy</a> · <a href="/imprint">Imprint</a></span></nav>${body}</div></body></html>`;

export function home({ scenes, today, price, publicUrl, purchase = null }) {
  const feed = scenes.map(s => `<div class="scene"><div>${esc(s.prompt_display)}</div><span class="status">${esc(s.status)}</span>${s.status === 'played' ? ` · <a href="/scene/${s.id}">watch</a>` : ''}</div>`).join('') || '<p class="muted">No scenes yet. The stage is yours.</p>';
  const banner = purchase
    ? `<div class="panel notice"><strong>Payment received — thank you.</strong>${purchase.id ? ` Your scene is <a href="/scene/${purchase.id}">#${purchase.id}</a> (status: ${esc(purchase.status)}).` : ' Your scene is being registered; it will appear in the feed shortly.'} We check the prompt against our content rules, generate roughly ${purchase.sceneSeconds} seconds of video and air it in the live stream — usually within a few minutes. If the prompt is rejected or generation fails, the full amount is refunded automatically to your payment method. Keep this page open or note the scene number to follow along.</div>`
    : '';
  return shell('Live', `${banner}<div class="hero"><section><div class="panel"><div class="live">LIVE</div><video id="player" controls autoplay muted playsinline></video><p class="muted">If playback has just started, the first HLS segments may take a few seconds.</p></div><h2>Recent scenes</h2><div class="panel">${feed}</div></section><aside><div class="panel"><h1>Buy the next scene — $${(price/100).toFixed(2)}</h1><form id="buy"><textarea name="prompt" minlength="10" maxlength="300" required placeholder="Describe a 15-second scene…"></textarea><p class="muted">10–300 characters. No real people, protected characters, sexual content, hate, harassment, or personal data.</p><button>Continue to payment</button><p id="error"></p></form><strong>${today} scenes today</strong><p class="muted">Total price $${(price/100).toFixed(2)}, including any VAT that applies to your country; the exact amount is shown at checkout. Every scene is AI-generated. Prompts are checked against our content rules after payment and before generation — rejected prompts never air and are refunded in full, as are scenes we fail to generate or broadcast. Only scenes that have been paid for and cleared moderation appear in the feed above.</p></div></aside></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/hls.js/1.6.13/hls.min.js"></script><script>const v=document.querySelector('#player'),u=${JSON.stringify(publicUrl + '/hls/live/stream/index.m3u8')};
if(window.Hls&&Hls.isSupported()){const h=new Hls({liveDurationInfinity:true});h.loadSource(u);h.attachMedia(v);h.on(Hls.Events.ERROR,(_e,d)=>{if(!d.fatal)return;if(d.type===Hls.ErrorTypes.NETWORK_ERROR){setTimeout(()=>{h.loadSource(u);h.startLoad()},2000)}else if(d.type===Hls.ErrorTypes.MEDIA_ERROR){h.recoverMediaError()}else{setTimeout(()=>location.reload(),5000)}})}
else{v.src=u;v.addEventListener('error',()=>setTimeout(()=>{v.src=u+'?t='+Date.now();v.load()},2000))}
document.querySelector('#buy').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:new FormData(e.target).get('prompt')})});const j=await r.json();if(r.ok)location.href=j.url;else{document.querySelector('#error').textContent=j.error;b.disabled=false}};</script>`);
}

export function scenePage(scene) { return shell(`Scene ${scene.id}`, `<main><h1>Scene #${scene.id}</h1><p>${esc(scene.prompt_display)}</p>${scene.status === 'played' ? `<video controls src="/media/scenes/${scene.id}.mp4"></video>` : `<div class="panel">Status: ${esc(scene.status)}</div>`}</main>`); }
export function privacy() { return shell('Privacy Policy', `<main class="legal"><h1>Privacy Policy</h1><p class="muted">Prompt Theater · Last updated: 29 August 2026</p><p>This policy describes what personal data Prompt Theater processes.</p><h2>Who is responsible</h2><p>The controller within the meaning of Art. 4(7) GDPR is:<br>productivity-boost.com Betriebs UG (haftungsbeschränkt) &amp; Co. KG<br>Reichenbergerstr. 2, 94036 Passau, Germany<br>Represented by Florian Standhartinger · Email: <a href="mailto:info@productivity-boost.com">info@productivity-boost.com</a></p><p>We have not appointed a data protection officer, as we are not required to under Art. 37 GDPR. You may lodge a complaint with the Bayerisches Landesamt für Datenschutzaufsicht (BayLDA), Ansbach, Germany.</p><h2>What we process</h2><p>When you purchase a scene, we process your prompt, payment-session identifiers, payment amount, scene status, generation output and technical timestamps to perform the contract (Art. 6(1)(b) GDPR), prevent abuse and operate the service (Art. 6(1)(f) GDPR). We do not use analytics or advertising trackers. Our hosting provider may process IP addresses in rotating security logs.</p><h2>Payment and generation providers</h2><p>Stripe acts as payment service provider and processes payment and checkout data under its own terms. We transmit your prompt to fal as our generation processor so that fal can create the requested video. Do not put personal data in a prompt. OpenRouter and the selected moderation model process prompts to check compliance before generation.</p><h2>Storage duration</h2><p>Payment and accounting records are retained for statutory retention periods. Audit records, prompts and generated scenes are retained while needed to operate the replay service, resolve disputes and prevent abuse, then deleted or anonymized. Rejected prompts and operational errors are deleted when no longer needed for refunds or dispute handling. You may request earlier deletion where no legal obligation requires retention.</p><h2>If you email us</h2><p>We process your email address and message to answer your request (Art. 6(1)(b) GDPR) and retain correspondence only as long as needed.</p><h2>Your rights</h2><p>You have rights of access, rectification, erasure, restriction, portability and objection under Arts. 15–21 GDPR. Contact <a href="mailto:info@productivity-boost.com">info@productivity-boost.com</a>.</p></main>`); }
export function imprint() { return shell('Imprint', `<main class="legal"><h1>Imprint</h1><p>Information in accordance with § 5 DDG (Digitale-Dienste-Gesetz).</p><h2>Provider</h2><p>productivity-boost.com Betriebs UG (haftungsbeschränkt) &amp; Co. KG<br>Reichenbergerstr. 2<br>94036 Passau<br>Germany</p><h2>Represented by</h2><p>Florian Standhartinger</p><h2>Contact</h2><p>Email: <a href="mailto:info@productivity-boost.com">info@productivity-boost.com</a><br>Telephone: +49 178 1981631</p><h2>Register entry</h2><p>Registered in the commercial register.<br>Register court: Amtsgericht Passau<br>Register number: HRB 8453</p><h2>VAT identification number</h2><p>VAT ID under § 27a UStG: DE296812612</p><h2>Responsible for editorial content</h2><p>Under § 18 Abs. 2 MStV: Florian Standhartinger, address as above.</p><h2>Online dispute resolution</h2><p>The European Commission provides a platform for online dispute resolution at <a href="https://ec.europa.eu/consumers/odr">ec.europa.eu/consumers/odr</a>. We are neither obliged nor willing to take part in dispute resolution proceedings before a consumer arbitration board.</p></main>`); }
